In [7]:
#creating ndarrays
#file input and output with arrays
import numpy as np
arr=np.arange(10)
np.save("some_array",arr)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.load("some_array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.savez("array_archive.npz",a=arr,b=arr)

In [10]:
arch=np.load("array_archive.npz")

In [11]:
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr1=np.array([1,5,6,7])
arr2=np.array([8,9,5,6])
np.savez("array_archive2.npz",a=arr1,b=arr2)

In [23]:
arch=np.load("array_archive2.npz")

In [24]:
arch['a']

array([1, 5, 6, 7])

In [25]:
arch['b']

array([8, 9, 5, 6])