1.Create a NumPy array

In [ ]:
import numpy as np
#Create a 1D array
arr1=np.array([1,2,3])
print(arr1)

[1 2 3]


2.Access and manipulate the elements of the array

In [ ]:
arr1[2]

3

In [ ]:
#change an element from an array
arr1[2]=5
arr1

array([1, 2, 5])

3.Create a 2-dimensional array and check the shape of the array

In [ ]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [ ]:
print("The shape is 2 rows and 3 columns:",arr2.shape)

The shape is 2 rows and 3 columns: (2, 3)


4.Access elements from the 2_d array using index positions

In [ ]:
print(arr2[0][2])
print(arr2[0,2])
print(arr2[0,-1])
print(arr2[-1,0])


3
3
3
4


5.Create an array of type string

In [ ]:
arr3=np.array(['India','China','USA','Mexico'])
print(arr3)

['India' 'China' 'USA' 'Mexico']


In [ ]:
arr3[1]

'China'

6.Using the arrange() and inspace() function to evenly space values in a specified interval

In [ ]:
arr=np.arange(0,20,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
arr=np.linspace(0,10,20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


7.Create an array of random values between 0 and1 in a given shape

In [ ]:
arr=np.random.rand(10)
print(arr)
print('\n')
arr=np.random.rand(3,4)
print(arr)

[0.01338364 0.90254865 0.98460943 0.38218569 0.55037737 0.229002
 0.89336686 0.76973608 0.96790017 0.51319064]


[[0.0868719  0.39673164 0.77738515 0.04911513]
 [0.95767511 0.93485992 0.73714122 0.94908229]
 [0.94592564 0.88748576 0.83061403 0.01190784]]


8.Create an array of constant values in a given shape

In [ ]:
print(np.full((4,6),10))

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


9.Repeat each element of an array by a specified number of times using repeat() and tile() function

In [ ]:
arr=[0,1,2]
print(np.repeat(arr,3))

[0 0 0 1 1 1 2 2 2]


In [ ]:
arr=[0,1,2]
print(np.tile(arr,3))

[0 1 2 0 1 2 0 1 2]


10.Create an identity matrix using eye() and identity() function

In [ ]:
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
identity_matrix=np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr=np.random.rand(5,5)
print(arr)

[[0.80072572 0.54181396 0.71260719 0.71414621 0.32349889]
 [0.15592859 0.21284605 0.75780561 0.20180932 0.44962986]
 [0.96825443 0.73345394 0.13316883 0.42604851 0.76471766]
 [0.47915932 0.05848932 0.31937342 0.69017773 0.54577721]
 [0.16624885 0.72193094 0.9748521  0.69746658 0.21048981]]


In [ ]:
print(np.sum(arr,axis=0))

[2.5703169  2.26853421 2.89780715 2.72964835 2.29411344]


In [ ]:
print(np.sum(arr,axis=1))

[3.09279197 1.77801944 3.02564336 2.09297699 2.77098828]


In [ ]:
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

0.5104168019216476
0.5418139648211502
0.2705187659478592
0.07318040272995262


In [ ]:
arr=np.random.rand(5,5)
print(arr)

[[0.38949352 0.14138213 0.16858982 0.53966574 0.36436769]
 [0.39906894 0.06879636 0.89597014 0.24104787 0.36247988]
 [0.08667679 0.37027118 0.14686893 0.00584893 0.26465934]
 [0.77574007 0.67389502 0.41997953 0.02363548 0.98102385]
 [0.67024126 0.00279631 0.43496807 0.57855431 0.950042  ]]


In [ ]:
print(np.sort(arr,axis=1))

[[0.14138213 0.16858982 0.36436769 0.38949352 0.53966574]
 [0.06879636 0.24104787 0.36247988 0.39906894 0.89597014]
 [0.00584893 0.08667679 0.14686893 0.26465934 0.37027118]
 [0.02363548 0.41997953 0.67389502 0.77574007 0.98102385]
 [0.00279631 0.43496807 0.57855431 0.67024126 0.950042  ]]


In [ ]:
arr=np.array([4,5,6,7])
arr1=np.append(arr,8)
arr1

array([4, 5, 6, 7, 8])

In [ ]:
arr2=np.append(arr,[9,10,11])
print(arr2)

[ 4  5  6  7  9 10 11]


In [ ]:
arr2=np.array([4,5,6,7,9,10,11])
print(arr2)
print("\n")
arr5=np.delete(arr2,[1,4])
print(arr5)

[ 4  5  6  7  9 10 11]


[ 4  6  7 10 11]


In [ ]:
arr1=np.array([[1,2,3,4],[1,2,3,4]])
arr2=np.array([[5,6,7,8],[5,6,7,8]])
cat=np.concatenate((arr1,arr2),axis=0)
print(cat)


[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [ ]:
cat=np.concatenate((arr1,arr2),axis=1)
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]
